作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [16]:
import numpy as np

In [18]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
#寫法一
#with open('save_array.npz', 'wb') as f:
#    np.savez(f, array1, array2)
#寫法二
np.savez('save_array.npz', array1, array2)

In [21]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
loadfile = np.load('save_array.npz')
type(loadfile)
loadfile.files
print(loadfile['arr_0'])
print(loadfile['arr_1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [22]:
array3 = np.arange(10)
#寫法一
with open('save_array.npz', 'wb') as f:
    np.savez(f, loadfile['arr_0'], loadfile['arr_1'], array3)

In [24]:
loadfile2 = np.load('save_array.npz')
type(loadfile2)
loadfile2.files

['arr_0', 'arr_1', 'arr_2']

In [25]:
print(loadfile2['arr_0'])
print(loadfile2['arr_1'])
print(loadfile2['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
